# Machine Learning 102 - Unsupervised - Hacker Dojo
# http://machinelearning102.pbworks.com/w/page/32890352/FrontPage
#
# Homework #4, Detecting Anomalies
# Dave Abercrombie, November 16 2011
#
# Part 2: look for anomalies in synthetic data from part 1.
#
#######################################################
# 1. Read the CSV generated by Part 1, peek at it

ls()
setwd("/Users/dabercrombie/Documents/aberdave-repos/Machine-Learning/ml102/hw4")

synthetic.data <- read.csv(
    file="synthetic.data.csv"
)
str(synthetic.data)

# note the two types of anomalies in the last 20 rows 
tail(x=synthetic.data, n=40)

# define two contiguous index ranges, one for typical
# and one for anomalous data
#
range.typical <- 1:980
range.anomaly <- 981:1000

# derive lengths of typcal and anomaly data
count.typical <- length(range.typical)
count.anomaly <- length(range.anomaly)



#######################################################
# 2. use e1071 to make an SVM one-class model

require("e1071")

# Generate model and extract training data predictions
synthetic.data.svm <- svm(
  x=synthetic.data,
  type="one-classification",
  # gamma = 0.1, 
  cost = 1,
  nu = 0.08
)
svm.model.predictions <- fitted(synthetic.data.svm)

# Since "typical" and anomaly data are each contiguous,
# we expect two thick strainght lines. Points by themselves
# along these lines are prediction errors
#
plot(svm.model.predictions,
     main="SVM one-class training predictions",
     sub="perfection would be two lines, no stray points"
)

# Anomalies should be flagged FALSE, so the sum of TRUE values
# is the count of incorrect anomaly predictions
#
misclassified.anomaly.count <- sum(svm.model.predictions[range.anomaly])

# Typical data should be flagged TRUE, so the sum of TRUE values
# is the count of correct "typical" predictions. To get the count
# of errors, we subtract this from the count of all typcal data
#
misclassified.typical.count <- count.typical - sum(svm.model.predictions[range.typical])

# How many errors did we make?
list(
    misclassified.anomaly.count=misclassified.anomaly.count, 
    misclassified.typical.count=misclassified.typical.count
)

# nu=0.08 and default gamma provide perfect detection of anomalies, with
# about a 6% error rate with typical data
